#!/bin/bash
# Generate Android app icons for Sereus Chat from the canonical SVG.
# Modelled on ser/health/apps/mobile/scripts/logo-gen-android.sh.
#
# Adaptive icons (API 26+): a background layer (solid brand colour) + a
# foreground layer (the logo, transparent around it). The OS masks the pair to
# the device shape (circle / squircle / rounded-square).
#
# Chat's mark is a GREEN DISC whose own left edge is the face profile, so the
# icon is that disc on a light background (not a white mark on green). The disc
# is inset to the adaptive safe zone (~66-80% of the 108dp canvas) so masks and
# the notch/face don't get clipped.
#
# Source:  docs/images/logo_3_m.svg  (green disc on transparent)
# Output:  mipmap-*/ic_launcher_foreground.png, legacy ic_launcher[_round].png,
#          values/ic_launcher_background.xml (colour), src/assets/logo.png

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"               # chat/apps/mobile
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"    # chat/
ASSETS_DIR="$PROJECT_ROOT/docs/images"
SRC="$ASSETS_DIR/logo_3_m.svg"

# --- knobs -----------------------------------------------------------------
BG_COLOR="#fdf8f0"   # icon background (peach, shared with the Sereus family)
FG_SCALE="0.80"      # disc size as a fraction of the adaptive canvas (safe zone)
# ---------------------------------------------------------------------------

echo "🎨 Generating Sereus Chat app icons (Android) from $(basename "$SRC")..."

command -v magick >/dev/null 2>&1 || { echo "❌ ImageMagick not found. brew install imagemagick"; exit 1; }
[ -f "$SRC" ] || { echo "❌ source not found: $SRC"; exit 1; }

cd "$APP_DIR"
RES=android/app/src/main/res
mkdir -p "$RES"/mipmap-{mdpi,hdpi,xhdpi,xxhdpi,xxxhdpi} "$RES/drawable" "$RES/values" src/assets

# density -> adaptive foreground px (108dp) : legacy launcher px
DENSITIES="mdpi:108:48 hdpi:162:72 xhdpi:216:96 xxhdpi:324:144 xxxhdpi:432:192"

echo "📱 Foreground layers + legacy composites..."
for d in $DENSITIES; do
  name="${d%%:*}"; rest="${d#*:}"; fg="${rest%%:*}"; legacy="${rest##*:}"
  inner=$(awk "BEGIN{printf \"%d\", $fg*$FG_SCALE}")
  fgpng="$RES/mipmap-$name/ic_launcher_foreground.png"

  # Adaptive foreground: disc inset to the safe zone, centered, transparent.
  magick -background none "$SRC" -resize "${inner}x${inner}" \
    -gravity center -extent "${fg}x${fg}" "$fgpng"

  # Legacy single-layer icon: brand square + the foreground scaled to fit.
  magick "(" -size "${legacy}x${legacy}" "xc:${BG_COLOR}" ")" \
         "(" "$fgpng" -resize "${legacy}x${legacy}" ")" \
         -gravity center -composite "$RES/mipmap-$name/ic_launcher.png"
  cp "$RES/mipmap-$name/ic_launcher.png" "$RES/mipmap-$name/ic_launcher_round.png"
done

# Keep the adaptive background colour in sync with BG_COLOR (single source).
cat > "$RES/values/ic_launcher_background.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- App-icon background. Generated by scripts/logo-gen-android.sh. -->
    <color name="ic_launcher_background">${BG_COLOR}</color>
</resources>
XML

echo "🖼️  In-app logo (transparent, for the themed header)..."
magick -background none "$SRC" -resize 108x108 src/assets/logo.png

echo "✅ Done. Static XML (adaptive-icon + background shape) lives in $RES/."
echo "   Rebuild to see the launcher icon:  cd android && ./gradlew clean && cd .. && yarn android"
